using System;
using System.ComponentModel;
using Startup;

namespace Chapter2.Objective5
{
    [Description("Listing 2-76 The automatically generated source file.")]
    internal class TheAutomaticallyGeneratedSourceFile : ISample
    {
        public void Run()
        {
            Console.WriteLine(
                @" //------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNamespace {
    using System;

    public class MyClass {       
        public static void Main() {
            Console.WriteLine(""Hello World!"");
        }
    }
} );");
        }
    }
}